### ISSUE TITLE
Plugin TypeError: Cannot read property 'parsed' of null

### ISSUE THREAD

**Issue by jainet** [AdobeXD/xd-to-flutter-plugin#78]
Describe the Bug
The following error occurs during the exporting of the artboard and it cannot export.

Plugin TypeError: Cannot read property 'parsed' of null
    at E (<settings>/plugins/6eaf77ea/main.js:1:72579)
    at P (<settings>/plugins/6eaf77ea/main.js:1:73861)
    at E (<settings>/plugins/6eaf77ea/main.js:1:72805)
    at e.parse (<settings>/plugins/6eaf77ea/main.js:1:72090)
    at Object.exportSelected (<settings>/plugins/6eaf77ea/main.js:1:70230)
    at async <settings>/plugins/6eaf77ea/main.js:1:45508

OS & XD Version:
OS: MacOS 10.15.7
XD: 34.4.12.3

**Comment by gskinner** [comment]
Any chance you can share the XD file that's causing this (ideally simplified as much as possible)? I can dig into why this might be happening, but having a file that concretely reproduces it would be very helpful.

Thanks!

**Comment by gskinner** [comment]
After digging through the code, my best guess is that this occurs due to a duplicate component name. It looks like the duplicate name gets caught correctly, but it fails a later dependency check.

I just pushed a fix for that, but I would still really like to get a sample file so I can be sure I'm not just treating the symptom of a larger problem (@jainet or @SpaceKestrel72).

**Comment by jainet** [comment]
Sorry I'm late.
I was able to import it by limiting it to a simple widget.
Thank you very much.
